theopenlane/openlane-ui

apps/console/src/components/pages/protected/developers/actions/pat-actions.tsx, apps/console/src/components/pages/protected/developers/api-token-form.tsx, apps/console/src/components/pages/protected/developers/api-tokens-table.tsx, apps/console/src/components/pages/protected/developers/personal-access-tokens-table.tsx, packages/codegen/query/apitokens.graphql, packages/codegen/src/schema.ts
=> feat: scopes for api tokens, fix delete of api tokens

apps/console/src/components/pages/protected/questionnaire/questionnaire-editor.tsx, config/.env-example, packages/dally/src/index.ts
Adds the ability to add a surveyJS license key
=> feat: add license key for survey js

apps/console/src/components/shared/sidebar/sidebar.styles.tsx
the sidebar is taking up a a lot of screen space, this decreases it some from 72px -> 60px
=> decrease sidebar nav size

.github/CONTRIBUTING.md, .gitignore, .pre-commit-config.yaml, README.md, Taskfile.yaml, packages/codegen/README.md, packages/codegen/graphql-codegen.yml
- Updates the main `README`
- Updates the `packages/codegen` repo for generating graphql functions
- Adds the `.github/Contributing` guide
=> Adds README + Contributing Guides

apps/console/src/components/shared/organization-selector/organization-selector.styles.tsx
=> fixes #85 - org switcher: set dark mode background

apps/console/src/app/(auth)/resend-verify/page.styles.tsx, apps/console/src/app/(auth)/resend-verify/page.tsx, apps/console/src/app/(auth)/verify/page.tsx, apps/console/src/app/(auth)/waitlist/page.tsx, apps/console/src/app/api/auth/resend/route.ts, apps/console/src/components/pages/auth/resend-verify/resend.styles.ts, apps/console/src/components/pages/auth/resend-verify/resend.tsx, apps/console/src/components/pages/auth/subscriber-verify/verifier.tsx, apps/console/src/components/pages/auth/verify/page.styles.tsx, apps/console/src/components/pages/auth/verify/verifier.tsx, apps/console/src/lib/user.ts, apps/console/src/middleware.ts
- Fixes the email verification page, it was pointing the subscriber verification page instead of signup verification
- Adds a resend email verification page
should resolve https://github.com/theopenlane/openlane-ui/issues/93
=> Fix email verify

apps/console/src/components/layouts/dashboard/dashboard.styles.tsx, apps/console/src/components/shared/sidebar/sidebar-nav/sidebar-nav.styles.tsx, apps/console/src/components/shared/sidebar/sidebar-nav/sidebar-nav.tsx, apps/console/src/components/shared/sidebar/sidebar.styles.tsx
=> Fix Tooltips

apps/console/src/components/pages/protected/organization/general-settings/organization-delete.tsx, apps/console/src/components/pages/protected/organization/general-settings/organization-email-form.tsx, apps/console/src/components/pages/protected/organization/general-settings/organization-name-form.tsx, apps/console/src/components/pages/protected/organization/members/actions/invite-actions.tsx, apps/console/src/components/pages/protected/organization/members/members-page.tsx, apps/console/src/lib/authz/utils.ts
=> fix permissions logic causing errors

apps/console/src/app/(protected)/dashboard/page.tsx, apps/console/src/components/pages/protected/dashboard/dashboard.tsx, apps/console/src/components/pages/protected/organization/billing/billing-contract-dialog.tsx, apps/console/src/components/pages/protected/organization/billing/billing-email-dialog.tsx, apps/console/src/components/pages/protected/organization/billing/billing-settings.tsx, apps/console/src/components/pages/protected/organization/billing/pricing-plan.tsx, packages/ui/src/badge/badge.tsx
added badges/status logic
added fallback for email and address
added more toast messages
=> Feat billing design changes

apps/console/src/app/(auth)/waitlist/page.tsx, apps/console/src/app/api/recaptchaVerify/route.ts, apps/console/src/app/globals.css, apps/console/src/app/layout.tsx, apps/console/src/app/providers.tsx, apps/console/src/components/pages/auth/login/login.tsx, apps/console/src/components/pages/auth/signup/signup.tsx, apps/console/src/components/pages/auth/subscribe/subscribe.tsx, config/.env.example, packages/codegen/src/schema.ts, packages/dally/src/index.ts
❌ ENV VARS ❌ 
`NEXT_PUBLIC_RECAPTCHA_SITE_KEY`
`RECAPTCHA_SECRET_KEY`
=> Feat recaptcha

apps/console/src/components/shared/header/header.tsx, apps/console/src/components/shared/sidebar/sidebar.styles.tsx, apps/console/src/components/shared/sidebar/sidebar.tsx
=> reposition shrink toggler

apps/console/src/app/(protected)/organization-settings/billing/page.tsx, apps/console/src/app/(protected)/organization-settings/general-settings/page.styles.tsx
=> wrapper fix

apps/console/src/components/shared/breadcrumb-nav/breadcrumb.tsx
=> separator change

apps/console/src/components/pages/protected/groups/my-groups/dialogs/assign-permissions-dialog.tsx, apps/console/src/components/pages/protected/groups/my-groups/my-groups-permissions-table.tsx, apps/console/src/constants/groups.ts
adds delete to the permissions table
fixes bug => default permission set was edit instead of view
=> Feat remove permissions

apps/console/src/components/pages/protected/program/dialog.styles.tsx, packages/ui/src/button/button.styles.tsx, packages/ui/src/confirmation-dialog/confirmation-dialog.stories.tsx, packages/ui/src/select/select.styles.tsx
next pr will be implementation of this popup
=> confirmation popup story and letter spacing

apps/console/src/app/(protected)/standards/page.tsx, apps/console/src/components/shared/table-filter/table-filter.tsx, apps/console/src/lib/graphql-hooks/standards.ts, packages/codegen/query/standards.ts, packages/codegen/src/schema.ts
=> Feat standards

packages/ui/src/multiple-selector/multiple-selector.tsx
fix for all multiple selectors:
=> fixing dynamic height

apps/console/src/app/(auth)/login/page.tsx, apps/console/src/components/pages/auth/login/login.tsx, apps/console/src/components/pages/auth/signup/signup.tsx, apps/console/src/components/pages/invite/accept.tsx, apps/console/src/components/pages/protected/organization/members/actions/member-actions.tsx, apps/console/src/lib/user.ts, apps/console/src/middleware.ts
1. user is logged in
2. user goes to /invite?token={:id}
3. session is updated and user is redirected to /dashboard
4. user's selected organization is the new invited one.
=> fixing logged in invite

apps/console/src/app/(auth)/login/page.tsx, apps/console/src/components/pages/invite/accept.tsx, apps/console/src/components/pages/protected/overview/my-task.tsx
=> fixing invites redirect to onboarding, fixing alignment on tasks

apps/console/src/components/pages/protected/organization/members/actions/invite-actions.tsx, apps/console/src/components/pages/protected/organization/members/organization-invites.tsx, apps/console/src/lib/graphql-hooks/organization.ts, packages/codegen/query/organization.ts, packages/codegen/src/schema.ts
resend invite logic
invalidating queries related to invites.
deleting invite fix
adding attempts in the table
=> resend invite

packages/ui/src/input/input.tsx
broke non-prefilled inputs yesterday
=> fixing input value set

apps/console/src/components/pages/protected/organization/members/actions/invite-actions.tsx, apps/console/src/components/pages/protected/organization/members/organization-invites.tsx
=> resend attempts and moving actions to last

packages/codegen/query/standards.ts, packages/codegen/src/schema.ts
adding to standards queries:
controls(where: { ownerIDIsNil: true }) {
totalCount
}
=> fixing standards query

apps/console/src/components/pages/protected/controls/controls-table.tsx, apps/console/src/components/pages/protected/standards/standard-details-accordion.tsx, apps/console/src/components/shared/objectAssociation/object-association-table.tsx, apps/console/src/lib/graphql-hooks/controls.ts, packages/codegen/query/control.ts, packages/codegen/src/schema.ts, packages/ui/package.json, packages/ui/src/data-table/data-table.tsx, packages/ui/src/pagination/pagination.tsx, packages/ui/src/pagination/types.ts
let's see performances of pagination
=> Feat pagination

apps/console/src/components/pages/protected/program/summary-card.tsx
=> fixing selected program type

apps/console/src/components/pages/protected/program/wizard.tsx
=> default value for audit period

apps/console/src/components/pages/protected/organization/billing/billing-settings.styles.tsx, apps/console/src/components/pages/protected/organization/billing/billing-settings.tsx, apps/console/src/components/pages/protected/organization/billing/pricing-plan.tsx, packages/codegen/query/organization.ts, packages/codegen/src/schema.ts
=> update billing with new links

apps/console/src/app/(auth)/forgot-password/page.tsx, apps/console/src/app/(auth)/password-reset/page.tsx, apps/console/src/app/providers.tsx, apps/console/src/components/pages/auth/login/login.tsx, apps/console/src/components/pages/auth/password-reset/page.tsx, apps/console/src/middleware.ts
=> Feat forgot password

apps/console/src/components/pages/auth/login/login.tsx
=> alignment of forgot pass

apps/console/src/components/pages/protected/tasks/create-task/sidebar/task-details-sheet.tsx
Resolves: https://github.com/theopenlane/openlane-ui/issues/338
=> task_due_date_format: fixed due date format on task details sheet

apps/console/src/app/(auth)/forgot-password/page.tsx, apps/console/src/components/pages/auth/login/login.tsx, apps/console/src/components/pages/auth/password-reset/page.tsx, apps/console/src/components/pages/auth/signup/signup.tsx
- fixes width of password reset email box
- switches to `PasswordInput` so the show/hide button is there
- Adding some text, small style changes
- `PassKey` -> `passkey`
=> fix width of password reset input, small styling

apps/console/src/components/pages/protected/policies/create/form/create-policy-form.tsx, apps/console/src/components/pages/protected/policies/view/fields/details-field.tsx, apps/console/src/components/pages/protected/procedures/create/form/create-procedure-form.tsx, apps/console/src/components/pages/protected/procedures/view/fields/details-field.tsx, packages/ui/src/components/plate-ui/editor.tsx, packages/ui/src/components/plate-ui/heading-element-static.tsx, packages/ui/src/components/plate-ui/heading-element.tsx
- Fixed scrollable plate editor (Now always pushes text area to the bottom)
- Removed extra margins from heading elements on plate editor
=> Plate editor fixes

apps/console/src/app/(auth)/login/page.tsx, apps/console/src/components/pages/protected/overview/risks.tsx, packages/ui/src/tabs/tabs.styles.tsx
=> fixing risks

apps/console/src/components/pages/protected/procedures/view/fields/details-field.tsx, apps/console/src/components/shared/breadcrumb-nav/breadcrumb.tsx, apps/console/src/lib/graphql-hooks/procedures.ts
- Removed default procedure header from procedure view
- Fixed breadcrumbs for procedures
=> Procedures Fixes

apps/console/src/components/shared/search/search.tsx
- Added search shortcut in search input
=> Search Shortcut

apps/console/src/app/(auth)/waitlist/page.tsx, apps/console/src/app/layout.tsx, apps/console/src/components/layouts/auth/auth.styles.tsx
=> Chore waitlist mobile

packages/ui/src/components/plate-ui/editor.tsx
- Fixed issue with action bars on plate editor (e.g. link was being under the top bar)
=> Plate Editor Fix

apps/console/src/components/shared/search/search.tsx, apps/console/src/components/shared/shortcut-suffix/shortcut-suffix.tsx, apps/console/src/components/shared/user-menu/user-menu.tsx, packages/ui/src/components/plate-ui/advanced-fixed-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/advanced-floating-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/basic-fixed-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/basic-floating-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/minimal-fixed-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/minimal-floating-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/standard-fixed-toolbar-buttons.tsx, packages/ui/src/components/plate-ui/standard-floating-toolbar-buttons.tsx, packages/ui/src/kbd/kbd.tsx
- Added shortcut suffix based on windows or mac
=> Shortcut Suffix

apps/console/src/app/(protected)/risks/page.tsx, apps/console/src/components/pages/protected/developers/table/personal-access-tokens-table.tsx, apps/console/src/components/pages/protected/groups/components/groups-members-table.tsx, apps/console/src/components/pages/protected/groups/components/groups-table.tsx, apps/console/src/components/pages/protected/organization/members/table/organization-invites-table.tsx
- removed defined texts for no data in datatable and use default one "no results"
=> Table no result text

apps/console/src/components/shared/header/header.tsx, apps/console/src/components/shared/user-menu/user-menu.styles.tsx, apps/console/src/components/shared/user-menu/user-menu.tsx, packages/codegen/src/schema.ts, packages/ui/src/dropdown-menu/dropdown-menu.styles.tsx
theme icon
font set to 14px instead of 12
icons size set to 14px instead of 12
removed margin from dropdown item and added padding (for better hover effect)
docs and feedback back to header (also added icons)
=> improvements

apps/console/src/components/pages/auth/subscribe/subscribe.tsx
minor text alterations for the waitlist sign up
=> minor text alterations for subscribers

apps/console/src/components/shared/stats-cards/stats-cards-styles.ts, apps/console/src/components/shared/stats-cards/stats-cards.tsx, apps/console/src/lib/graphql-hooks/programs.ts, apps/console/tailwind.config.ts, packages/codegen/query/programs.ts, packages/codegen/src/schema.ts
- stats cards for programs
-stats cards for dashboard
-removed hardcoded data
-commented out a part of code that can't be used at the moment.
=> fixing stats for dashboard

apps/console/src/app/(protected)/dashboard/page.tsx
Align to the left, this matches what we have on the programs dashboard
=> align programs dropdown on dashboard to match programs page (left)

apps/console/src/components/pages/protected/policies/table/columns.tsx, apps/console/src/components/pages/protected/policies/table/policies-table.tsx, apps/console/src/components/pages/protected/procedures/table/columns.tsx, apps/console/src/components/pages/protected/procedures/table/procedures-table.tsx, packages/codegen/query/policy.ts, packages/codegen/query/procedure.ts, packages/codegen/src/schema.ts
=> add summary to ui for both procedure and policies 

apps/console/src/lib/authz/utils.ts
breaking change in this PR: https://github.com/theopenlane/core/pull/700
=> fix: breaking change to backend for account roles

apps/console/src/components/pages/protected/program/wizard.tsx, apps/console/src/components/pages/protected/program/wizard/step-1-init.tsx, packages/codegen/src/schema.ts
requires https://github.com/theopenlane/core/pull/727
=> Feat : allow user clone controls from a standard when creating a program

apps/console/src/components/pages/protected/organization/subscribers/table/columns.tsx
delete subscriber fixed
resolves: https://github.com/theopenlane/openlane-ui/issues/423
=> issue #423

apps/console/src/components/pages/protected/overview/my-task.tsx
tasks on dashboard colors and count fix
resolves: https://github.com/theopenlane/openlane-ui/issues/421
=> issue #421

apps/console/src/components/pages/protected/controls/table/controls-table.tsx, apps/console/src/components/pages/protected/overview/my-task.tsx
- cleans up the controls table, removes type for now
- fixes ordering of upcoming tasks on the dashboard which were backwards
=> controls table cleanup + upcoming tasks bug

apps/console/src/components/pages/protected/program/wizard.tsx, apps/console/src/components/pages/protected/program/wizard/step-1-init.tsx
resolves:  `Optionally allow users to select a framework when a program of type "Gap Analysis" is selected. It should not be required like it is for a Framework program.`
bonus:
added custom error messages on form validation
=> program wizzard improvements

apps/console/src/app/(protected)/controls/[id]/[subcontrolId]/page.tsx, apps/console/src/app/(protected)/controls/[id]/page.tsx, apps/console/src/components/pages/protected/tasks/create-task/dialog/create-task-dialog.tsx, apps/console/src/components/pages/protected/tasks/create-task/form/create-task-form.tsx, apps/console/src/components/pages/protected/tasks/create-task/sidebar/task-details-sheet.tsx, apps/console/src/components/pages/protected/tasks/hooks/use-form-schema.ts, apps/console/src/components/shared/objectAssociation/object-assoiation-config.ts, apps/console/src/lib/graphql-hooks/tasks.ts
task create from controls
invaldiations
fix zod schema
=> create task from controls

apps/console/src/components/pages/protected/organization/members/organization-invite-form.tsx
fixed emails not clearing on invitations when successful response
Resolves: https://github.com/theopenlane/openlane-ui/issues/459
=> Issue #459

packages/ui/src/components/plate-ui/editor.tsx
pasting large policy off screen editor fix
Resolves: https://github.com/theopenlane/openlane-ui/issues/433
=> Issue_#433

apps/console/src/components/pages/protected/groups/components/dialogs/add-members-dialog.tsx
- too many state re-renders because of the new edges 
- adding and deleting users from groups fixes too
https://github.com/user-attachments/assets/6e1cd909-c9b7-436e-b8f7-87ecfdc386fc
=> Fix multiple rerenders because of state changes

apps/console/src/components/pages/protected/controls/associated-objects-accordion.tsx, apps/console/src/components/pages/protected/policies/accordion/associated-objects-view-accordion.tsx, apps/console/src/components/pages/protected/procedures/accordion/associated-objects-view-accordion.tsx
=> redesign of associated object accordion

apps/console/src/components/pages/protected/controls/properties-card.tsx, apps/console/src/components/pages/protected/controls/table/table-config.ts, apps/console/src/components/shared/icon-enum/control-enum.tsx
- added not implemented status on edit 
- changed not implemented status icon
=> Control status - Not implemented

apps/console/src/components/pages/protected/controls/control-implementation/control-implementation-page.tsx, apps/console/src/components/pages/protected/controls/control-implementation/form/create-control-implementation-form.tsx
=> control implementations improvemens

apps/console/src/app/layout.tsx, apps/console/src/middleware.ts
Preview works on post inspector at least:
=> use cf image, don't redirect for waitlist

apps/console/src/app/layout.tsx
=> remove url, it might be conflicting

apps/console/src/components/pages/protected/controls/control-evidence/evidence-details-sheet.tsx
- fixed issue with not loading collection procedure on edit
- added labels to description and collection procedure
=> Evidence Sheet Fixes

apps/console/src/components/pages/protected/standards/add-to-organization-dialog.tsx, apps/console/src/components/pages/protected/standards/columns.tsx, apps/console/src/components/pages/protected/standards/standard-details-accordion.tsx, packages/ui/src/data-table/data-table.tsx
- repalcing table with DataTable compoennt
- DataTable extended with new footer prop
- redesign of add to org dialog
- refactored code into smaller components
=> standards - add to organization

apps/console/src/app/(protected)/controls/[id]/[subcontrolId]/page.tsx, apps/console/src/app/(protected)/controls/[id]/page.tsx, apps/console/src/components/pages/protected/controls/properties-card.tsx, packages/codegen/query/control.ts, packages/codegen/query/subcontrol.ts, packages/codegen/src/schema.ts
- properties card connected with api data (source and controlType)
- edit logic for source === framework
=> edit control rework permissions

apps/console/src/components/pages/programs/programs-tasks-table.tsx, apps/console/src/components/pages/protected/controls/properties-card.tsx, apps/console/src/components/pages/protected/overview/my-task.tsx, apps/console/src/components/pages/protected/tasks/cards/task-cards.tsx, apps/console/src/components/pages/protected/tasks/create-task/sidebar/task-details-sheet.tsx, apps/console/src/components/pages/protected/tasks/table/tasks-table.tsx, apps/console/src/utils/getHrefForObjectType.ts
tasks refactor using id parameter tasks?id=[:id]
also removed framewok from control selection
=> tasks refactor

apps/console/src/components/shared/objectAssociation/object-association-table.tsx
fixing rendering html in description column
=> description from plate ui render

apps/console/src/components/shared/sidebar/sidebar-nav/sidebar-nav.styles.tsx
- fixed colors of icons on nav bar
=> Icon colors Navigation

apps/console/src/components/pages/protected/policies/create/cards/status-card.tsx, apps/console/src/components/pages/protected/policies/create/form/create-policy-form.tsx, apps/console/src/components/pages/protected/policies/create/hooks/use-form-schema.ts, apps/console/src/components/pages/protected/policies/view/cards/authority-card.tsx, apps/console/src/components/pages/protected/procedures/create/cards/status-card.tsx, apps/console/src/components/pages/protected/procedures/create/form/create-procedure-form.tsx, apps/console/src/components/pages/protected/procedures/create/hooks/use-form-schema.ts, apps/console/src/components/pages/protected/procedures/view/cards/authority-card.tsx
- added approver and delegate on policy and procedure creation forms
=> policy-procedures-authority:

apps/console/src/components/pages/protected/controls/control-implementation/form/create-control-implementation-form.tsx, apps/console/src/components/pages/protected/controls/properties-card.tsx
- also update Reference ID to `Ref ID` and Auditor Reference ID to `Auditor ID` to keep them in a single row on a laptop display
=> update control implementation details field header

apps/console/src/components/pages/protected/controls/control-implementation/form/create-control-implementation-form.tsx, apps/console/src/components/pages/protected/controls/control-objectives/control-objective-page.tsx, apps/console/src/components/pages/protected/controls/control-objectives/form/create-control-objective-form.tsx
- Adds info help text, small wording changes
=> small updates to control implementation + objective

apps/console/src/components/pages/protected/groups/groups-page.tsx
=> Column icon misaligned on groups page

packages/ui/src/calendar-popover/calendar-popover.tsx
set date to a default value when calendar opened
=> Renewal date should be able to be set before default

apps/console/src/components/pages/protected/program/wizard/step-1-init.tsx
=> Create New Program: (i) in Form: Click behavior

apps/console/src/components/shared/header/header.tsx, apps/console/src/components/shared/organization/existing-organizations/existing-organizations.tsx
query fixed and removed some unused code
=> Organization page doesn't load existing orgs

apps/console/src/components/shared/organization-selector/organization-selector.tsx
=> Org Switcher should close after selecting

apps/console/src/components/pages/protected/program/wizard/step-1-init.tsx, apps/console/src/components/pages/protected/program/wizard/step-2-details.tsx
css on program wizard modified
=> Program Wizard - formatting

apps/console/src/app/(protected)/controls/[id]/[subcontrolId]/page.tsx, apps/console/src/app/(protected)/controls/[id]/page.tsx, apps/console/src/components/pages/programs/settings/danger-zone/program-settings-danger-zone.tsx, apps/console/src/components/pages/programs/settings/groups/program-settings-groups.tsx, apps/console/src/components/pages/programs/settings/users/program-settings-users.tsx, apps/console/src/components/pages/protected/controls/control-evidence/control-evidence-files.tsx, apps/console/src/components/pages/protected/controls/control-evidence/evidence-details-sheet.tsx, apps/console/src/components/pages/protected/controls/delete-control-dialog.tsx, apps/console/src/components/pages/protected/controls/delete-subcontrol-dialog.tsx, apps/console/src/components/pages/protected/developers/actions/pat-actions.tsx, apps/console/src/components/pages/protected/developers/table/personal-access-tokens-table.tsx, apps/console/src/components/pages/protected/organization/general-settings/organization-delete.tsx, apps/console/src/components/pages/protected/organization/members/actions/member-actions.tsx, apps/console/src/components/pages/protected/organization/members/members-table.tsx, apps/console/src/components/pages/protected/organization/subscribers/actions/subscriber-actions.tsx, apps/console/src/components/pages/protected/policies/view/view-policy-page.tsx, apps/console/src/components/pages/protected/procedures/view/view-procedure-page.tsx, apps/console/src/components/pages/protected/risks/view/view-risks-page.tsx, apps/console/src/components/pages/protected/tasks/create-task/dialog/delete-task-dialog.tsx, packages/ui/src/alert-dialog/alert-dialog.tsx, packages/ui/src/confirmation-dialog/confirmation-dialog.tsx
=> Confirm Delete dialogs

apps/console/src/components/pages/protected/program/wizard/step-1-init.tsx
=> Rearange fields for program create step 1

apps/console/src/components/shared/organization/create-organization/create-organization.tsx
dashboard refresh after creating an org
=> Fix for dashboard refresh after creating an organization

apps/console/src/components/pages/protected/controls/table/table-config.ts
category and subcategory added as filters on controls
=> Controls category and subcategory filters

apps/console/src/app/(protected)/programs/page.tsx, apps/console/src/components/pages/protected/dashboard/set-auditor-dialog.tsx
wrong field fix and tooltip autoshow fix
=> Auditor field and tooltip

apps/console/src/components/pages/protected/controls/edit-map-control/edit-map-control-page.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-controls-card.tsx, apps/console/src/components/pages/protected/controls/mapped-relationships-sheet.tsx, apps/console/src/components/pages/protected/controls/related-controls.tsx, apps/console/src/components/shared/icon-enum/map-control-enum.tsx, apps/console/src/lib/graphql-hooks/mapped-control.tsx, packages/codegen/query/mapped-control.ts, packages/codegen/src/schema.ts
better query invalidation
perfill form enirely (we had missing fields)
edit link on relations
when FROM or TO are collapsed we show max 5 control chips and we show + rest number
after mapUpdater edirect to control/subcontrol with opened relations sheet
fixing superset size
=> Chore map controls improvements

apps/console/src/components/shared/menu/menu.tsx, apps/console/src/components/shared/table-filter/advanced-filter-popover.tsx, apps/console/src/components/shared/table-filter/regular-filter-popover.tsx, apps/console/src/components/shared/table-filter/table-filter.tsx
- Closed Filter menu upon selection, and auto open filter form for selected filter
- Fixed save on "Enter"
- Added advanced filter remove button
- Fixed trash button to delete filter if there is last filter in the list
- Fixed cancel button not removing filter form if there is no data but was recently added.
=> Filters fixes

packages/ui/src/styles.css, packages/ui/src/table/table-styles.tsx
=> Table font bg and separator

apps/console/src/components/pages/protected/controls/edit-map-control/edit-map-control-page.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-control-categories-accordion.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-control-frameworks-accordion.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-control-page.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-control-results.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-controls-card.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-controls-relations.tsx, apps/console/src/components/pages/protected/controls/map-controls/matched-controls.tsx, apps/console/src/components/pages/protected/controls/map-controls/shared/control-chip.tsx, apps/console/src/components/pages/protected/controls/map-controls/shared/use-selectable-controls.ts, apps/console/src/components/shared/context-menu/context-menu.tsx, apps/console/src/types/index.tsx, packages/codegen/query/control.ts, packages/codegen/query/mapped-control.ts, packages/codegen/query/subcontrol.ts, packages/codegen/src/schema.ts
- multiselect
- right click dropdown
- optimizations
=> Feat multiselect map controls

apps/console/src/components/pages/auth/subscribe/subscribe.tsx, apps/console/src/components/pages/protected/onboarding/step-1.tsx
waitlist error check
domain add fix
=> fixing error check and domain add

apps/console/src/components/pages/protected/standards/columns.tsx, apps/console/src/components/pages/protected/standards/standard-details-accordion.tsx, packages/ui/src/table/table-styles.tsx
check all logic changed and tables shrunk down to 70% of the viewport
=> Standards check all logic

apps/console/src/components/pages/protected/controls/edit-map-control/edit-map-control-page.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-control-page.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-controls-card.tsx, apps/console/src/components/pages/protected/controls/map-controls/map-controls-form-filters.tsx, apps/console/src/components/pages/protected/controls/map-controls/matched-controls.tsx, bun.lock
Don't allow mapping of controls from same framework, but allow CUSTOM
=> Feat map controls query

apps/console/src/components/pages/protected/evidence/table/evidence-table.tsx
-  fixed calling evidence service before program ID is loaded
=> evidence_query_fix

apps/console/src/components/pages/protected/program/wizard/step-1-init.tsx
added logic when gap analysis is selected with framework
=> Default Program Name - Gap Analysis

apps/console/src/components/pages/protected/standards/standard-details-accordion.tsx
=> Standard details button height

apps/console/src/components/pages/programs/settings/danger-zone/program-settings-danger-zone.tsx, apps/console/src/components/pages/protected/program/wizard/step-4-associate.tsx, packages/tailwind-config/tailwind.config.ts, packages/ui/src/styles.css
=> Program button fix

apps/console/src/components/pages/protected/controls/map-controls/shared/control-chip.tsx, apps/console/src/components/pages/protected/controls/mapped-relations-card.tsx, apps/console/src/components/pages/protected/controls/properties-card.tsx, apps/console/src/components/pages/protected/controls/related-controls.tsx, apps/console/src/components/pages/protected/controls/table/table-config.tsx, apps/console/src/components/pages/protected/standards/shared/standard-chip.tsx, apps/console/src/components/pages/protected/standards/standard-details-card.tsx, packages/codegen/query/control.ts
standard chip implementation and control view associated objects tooltip fix
=> Standard chip implementation and associated objects tooltip fix

apps/console/src/components/shared/search/search.tsx, apps/console/src/lib/graphql-hooks/search.ts, packages/codegen/query/search.ts, packages/codegen/src/schema.ts
=> Fix search result names

apps/console/src/components/pages/protected/dashboard/program-auditor.tsx, apps/console/src/components/pages/protected/dashboard/set-auditor-dialog.tsx, apps/console/src/components/pages/protected/evidence/chart/evidence-status-chip.tsx, apps/console/src/components/pages/protected/evidence/evidence-create-form.tsx, apps/console/src/components/pages/protected/evidence/evidence-details-page.tsx, apps/console/src/components/pages/protected/evidence/table/evidence-table.tsx, apps/console/src/components/shared/stats-cards/stats-cards.tsx, apps/console/src/lib/graphql-hooks/evidence.ts, packages/codegen/query/evidence.ts, packages/codegen/src/schema.ts
auditor edit fix, auditor allow empty fields, evidence filters and evidence click from dashboard and programs
=> Set auditor and evidence cards

apps/console/src/components/shared/sidebar/sidebar-nav/sidebar-nav.styles.tsx
=> Sidebar hover style

apps/console/src/components/shared/sidebar/sidebar-nav/sidebar-nav.tsx
=> bottom_sidebar_fix: fixed bottom left sidebar style

apps/console/src/app/(protected)/controls/[id]/[subcontrolId]/control-implementation/page.tsx, apps/console/src/app/(protected)/controls/[id]/[subcontrolId]/control-objectives/page.tsx, apps/console/src/app/(protected)/controls/[id]/control-implementation/page.tsx, apps/console/src/app/(protected)/controls/[id]/control-objectives/page.tsx, apps/console/src/components/pages/protected/controls/control-implementation/control-implementation-page.tsx, apps/console/src/components/pages/protected/groups/groups-page.tsx, apps/console/src/components/pages/protected/standards/add-to-organization-dialog.tsx, apps/console/src/components/pages/protected/tasks/table/task-table-toolbar.tsx, apps/console/src/components/shared/menu/menu.tsx, apps/console/src/components/shared/slide-bar/slide-bar.tsx, apps/console/src/components/shared/table-card-view/table-card-view.tsx, packages/ui/src/button/button.styles.tsx, packages/ui/src/button/button.tsx
aria label, tooltip on buttons w/o text and metadata for control objectives and implementations
=> Feature buttons accessibility features and descriptive text

apps/console/src/components/pages/protected/controls/control-implementation/control-implementation-card.tsx, apps/console/src/components/pages/protected/controls/control-objectives/control-objective-card.tsx, apps/console/src/components/pages/protected/controls/map-controls/shared/control-chip.tsx, packages/codegen/query/control-implementation.ts, packages/codegen/query/control-objective.ts, packages/codegen/src/schema.ts
Replaced old chips w new ones with control + standard
=> Improvement controls implementations objectives standard chips

apps/console/src/components/shared/organization/create-organization/create-organization.tsx, apps/console/src/constants/graphQlResponseError.ts, apps/console/src/utils/graphQlErrorMatcher.ts
create org name already exists error handling
=> Clear message when org name already exists

apps/console/src/components/pages/protected/controls/map-controls/shared/control-chip.tsx
=> Control chip clip behavior

apps/console/src/components/pages/protected/controls/properties-card.tsx
=> Controls and subcontrols create fields out of card

apps/console/src/components/pages/protected/controls/map-controls/shared/control-chip.tsx, bun.lock
fixing tooltip width
Closes ISS-97
=> control chip tooltip fix

apps/console/src/components/pages/protected/risks/table/columns.tsx
=> ISS-43: Risks table likelihood and business costs fields

apps/console/src/components/pages/protected/controls/control-evidence/control-evidence-renew-dialog.tsx, apps/console/src/components/pages/protected/controls/control-evidence/evidence-details-sheet.tsx, apps/console/src/lib/authz/access-api.ts, bun.lock
=> evidence permissions and buttons

apps/console/src/hooks/useSubscriptionBanner.ts, packages/codegen/query/organization.ts, packages/codegen/src/schema.ts
schema changed and this request was error all the time
=> fixing payment method error

apps/console/src/app/api/auth/authentication-verification/route.ts, apps/console/src/app/api/auth/registration-verification/route.ts
This was breaking the passkeys registration
=> JSON requests only allowed

apps/console/src/components/pages/protected/standards/standard-details-accordion.tsx, packages/ui/src/input/input.tsx
Reverts theopenlane/openlane-ui#875
=> Revert "ISS-330 Standards Search Box Hightlighted"

apps/console/src/components/pages/protected/tasks/create-task/form/create-task-form.tsx, apps/console/src/hooks/useNotification.tsx
link added to success notification
=> Create Task Toast ISS-347

apps/console/src/components/pages/protected/controls/control-evidence/evidence-details-sheet.tsx, apps/console/src/components/pages/protected/controls/control-objectives/form/create-control-objective-form.tsx, apps/console/src/components/pages/protected/controls/create-control/create-control-form.tsx, apps/console/src/components/pages/protected/evidence/table/evidence-table.tsx, apps/console/src/components/pages/protected/groups/components/dialogs/create-group-dialog.tsx, apps/console/src/components/pages/protected/standards/standard-details-accordion.tsx, apps/console/src/components/pages/protected/tasks/create-task/form/fields/related-objects.tsx, apps/console/src/utils/getHrefForObjectType.ts, packages/codegen/query/tasks.ts, packages/codegen/src/schema.ts, packages/ui/src/input/input.tsx
tasks associated objects links for evidence and control objectives added
=> ISS-328 tasks associated objects links for evidence and control objectives

apps/console/src/components/shared/object-association/object-association-graph.tsx
=> Associated objects hover behind buttons - ISS-303

apps/console/src/components/shared/object-association/object-association-graph.tsx
=> More tooltips on object association ISS-388

apps/console/src/components/pages/protected/control-report/control-report-page.tsx
accordion content removed if w/o controls
=> Control Report No Category Empty ISS-380

apps/console/src/components/pages/protected/controls/control-evidence/control-evidence-table.tsx
=> Evidence should be clickable -> linked to evidence ISS-418

apps/console/src/components/pages/protected/controls/control-evidence/evidence-details-sheet.tsx
=> URL on evidence expands over other text ISS-417

apps/console/src/components/pages/protected/evidence/evidence-create-form.tsx
=> Redirect to new evidence after creation ISS-431

apps/console/src/app/(auth)/login/sso/page.tsx, apps/console/src/components/pages/auth/login/login.tsx, apps/console/src/lib/auth/auth.ts, apps/console/src/lib/auth/utils/get-openlane-token.ts, apps/console/src/lib/auth/utils/parse-response-cookies.ts, bun.lock
=> Enforce sso even if oauth2 authentication

apps/console/src/components/pages/protected/evidence/evidence-create-sheet.tsx
controls accordion always open
=> Linked controls should always be expanded ISS-506

apps/console/src/components/pages/protected/evidence/evidence-create-sheet.tsx, apps/console/src/components/shared/objectAssociation/object-association-controls-columns.tsx, packages/codegen/query/subcontrol.ts, packages/codegen/src/schema.ts
=> Adding a subcontrol comes through as `Custom` Framework ISS-507

apps/console/src/components/shared/lib/export.ts
=> Evidence Download All only downloads the first file ISS-512

apps/console/src/components/pages/protected/evidence/evidence-details-sheet.tsx, apps/console/src/components/pages/protected/evidence/evidence-renew-dialog.tsx
evidence view and edit redesign
=> Evidence View + Edit Redesign ISS-495

apps/console/src/app/(auth)/login/sso/enforce/page.tsx, apps/console/src/components/layouts/dashboard/dashboard.tsx, apps/console/src/components/pages/protected/controls/create-control/create-control-form.tsx, apps/console/src/components/pages/protected/controls/mapped-categories-dialog.tsx, apps/console/src/components/pages/protected/developers/personal-access-token-create-dialog.tsx, apps/console/src/components/pages/protected/evidence/evidence-details-page.tsx, apps/console/src/components/pages/protected/evidence/evidence-details-sheet.tsx, apps/console/src/components/pages/protected/profile/user-settings/passkeys-section.tsx, apps/console/src/components/pages/protected/profile/user-settings/profile-page.tsx, apps/console/src/components/pages/protected/profile/user-settings/qrcode-dialog.tsx, apps/console/src/components/pages/protected/standards/shared/standard-chip.tsx, apps/console/src/components/pages/protected/trust-center/settings/brand-section.tsx, apps/console/src/components/shared/avatar-upload/avatar-upload.tsx, apps/console/src/components/shared/objectAssociation/object-association-programs-chips.tsx, apps/console/src/components/shared/objects-chip/objects-chip.tsx, apps/console/src/components/shared/relations-accordion-trigger.tsx/relations-accordion-trigger.tsx, apps/console/src/components/shared/session-expired-modal/session-expired-modal.tsx, apps/console/src/components/shared/sidebar/sidebar-nav/sidebar-nav.tsx, apps/console/src/components/shared/slide-bar/slide-bar.tsx, apps/console/src/routes/dashboard.tsx, bun.lock, packages/ui/src/badge/badge.tsx, packages/ui/src/dialog/dialog.styles.tsx, packages/ui/src/dialog/dialog.tsx, packages/ui/src/multiple-selector/multiple-selector.tsx, packages/ui/src/styles.css
- fixed bg linked programs
- fixed sso page colors
- fixed pass key color tags
- fixed navigation side menus
- fixed evidence center button
- fixed chips
- fixed resizable sidebar styles
- fixed trust center buttons
- fixed evidence sheet inputs
=> ISS-549|ISS-548|ISS-545|ISS-544|ISS-543|ISS-542|ISS-541|ISS-540|ISS-535|ISS-534 

apps/console/src/components/pages/programs/programs-tasks-table.tsx, apps/console/src/components/pages/protected/control-report/control-report-page.tsx, apps/console/src/components/pages/protected/controls/create-control/create-control-form.tsx, apps/console/src/components/pages/protected/evidence/chart/evidence-status-chip.tsx, apps/console/src/components/pages/protected/overview/my-task.tsx, apps/console/src/components/pages/protected/overview/risks.tsx, apps/console/src/components/pages/protected/programs/controls-summary-card.tsx, apps/console/src/components/pages/protected/tasks/create-task/dialog/create-task-dialog.tsx, apps/console/src/components/pages/protected/tasks/table/task-table-toolbar.tsx, apps/console/src/components/shared/protected-area/protected-area.tsx, apps/console/src/components/shared/stats-cards/stats-cards.tsx, apps/console/src/components/shared/table-filter/filter-storage.ts, apps/console/src/components/shared/table-filter/table-filter.tsx, bun.lock
-  fixed all routes that are passing filters and extra params
=> route-redirect-fixes

apps/console/src/components/pages/protected/evidence/table/columns.tsx, apps/console/src/components/pages/protected/organization/members/table/columns.tsx, apps/console/src/components/pages/protected/policies/create/form/create-policy-upload-dialog.tsx, apps/console/src/components/pages/protected/policies/table/columns.tsx, apps/console/src/components/pages/protected/procedures/create/form/create-procedure-upload-dialog.tsx, apps/console/src/components/pages/protected/procedures/table/columns.tsx, apps/console/src/components/pages/protected/risks/risk-label.tsx, apps/console/src/components/pages/protected/risks/risks.ts, apps/console/src/components/pages/protected/risks/table/risks-table-toolbar.tsx, apps/console/src/components/shared/enum-mapper/control-enum.tsx, apps/console/src/components/shared/enum-mapper/evidence-enum.tsx, apps/console/src/components/shared/enum-mapper/invitation-enum.tsx, apps/console/src/components/shared/enum-mapper/policy-enum.tsx, apps/console/src/components/shared/enum-mapper/program-enum.tsx, apps/console/src/components/shared/enum-mapper/risk-enum.tsx, apps/console/src/components/shared/enum-mapper/task-enum.tsx, apps/storybook/.storybook/style.css, packages/ui/src/styles.css
=> Color code all status icons ISS-447

apps/console/src/components/pages/protected/organization/authentication/allowed-domains.tsx
=> Add toggle to allow auto-join on organization ISS-575

apps/console/src/components/pages/protected/organization/authentication/sso.tsx
=> Update SSO Provider Enums to not have underscores ISS-482
